"""Unit tests for translate status dictionary metadata."""

from __future__ import annotations

from app.translate.domain.constants import (
    DOC_TRANSLATE_SEGMENT_DONE,
    DOC_TRANSLATE_SEGMENT_FAILED,
    DOC_TRANSLATE_SEGMENT_PENDING,
    DOC_TRANSLATE_STATUS_ASSEMBLING,
    DOC_TRANSLATE_STATUS_EXTRACTING,
    DOC_TRANSLATE_STATUS_FAILED,
    DOC_TRANSLATE_STATUS_OCR_RUNNING,
    DOC_TRANSLATE_STATUS_PENDING,
    DOC_TRANSLATE_STATUS_SUCCESS,
    DOC_TRANSLATE_STATUS_TRANSLATING,
    TRANSLATE_SEGMENT_STATUS_DICT_CODE,
    TRANSLATE_SEGMENT_STATUS_DICT_ITEMS,
    TRANSLATE_STATUS_DICT_CODE,
    TRANSLATE_STATUS_DICT_ITEMS,
)


def test_translate_status_dict_metadata() -> None:
    """Dict codes and item codes align with job status constants."""

    assert TRANSLATE_STATUS_DICT_CODE == "TRANSLATE_STATUS"
    assert TRANSLATE_SEGMENT_STATUS_DICT_CODE == "TRANSLATE_SEGMENT_STATUS"
    assert set(TRANSLATE_STATUS_DICT_ITEMS) == {
        DOC_TRANSLATE_STATUS_PENDING,
        DOC_TRANSLATE_STATUS_OCR_RUNNING,
        DOC_TRANSLATE_STATUS_EXTRACTING,
        DOC_TRANSLATE_STATUS_TRANSLATING,
        DOC_TRANSLATE_STATUS_ASSEMBLING,
        DOC_TRANSLATE_STATUS_SUCCESS,
        DOC_TRANSLATE_STATUS_FAILED,
    }
    assert set(TRANSLATE_SEGMENT_STATUS_DICT_ITEMS) == {
        DOC_TRANSLATE_SEGMENT_PENDING,
        DOC_TRANSLATE_SEGMENT_DONE,
        DOC_TRANSLATE_SEGMENT_FAILED,
    }
