"""Status codes, file limits, and Celery task name for document translation."""

from __future__ import annotations

DOC_TRANSLATE_RUN_TASK_NAME = "translate.run_job"

DOC_TRANSLATE_ALLOWED_EXTS = frozenset({
    "doc",
    "docx",
    "pdf",
    "txt",
    "md",
    "csv",
    "xls",
    "xlsx",
})

DOC_TRANSLATE_STATUS_PENDING = "PENDING"
DOC_TRANSLATE_STATUS_OCR_RUNNING = "OCR_RUNNING"
DOC_TRANSLATE_STATUS_EXTRACTING = "EXTRACTING"
DOC_TRANSLATE_STATUS_TRANSLATING = "TRANSLATING"
DOC_TRANSLATE_STATUS_ASSEMBLING = "ASSEMBLING"
DOC_TRANSLATE_STATUS_SUCCESS = "SUCCESS"
DOC_TRANSLATE_STATUS_FAILED = "FAILED"

DOC_TRANSLATE_SEGMENT_PENDING = "PENDING"
DOC_TRANSLATE_SEGMENT_DONE = "DONE"
DOC_TRANSLATE_SEGMENT_FAILED = "FAILED"

DOC_TRANSLATE_MAX_FILE_BYTES = 20 * 1024 * 1024
DOC_TRANSLATE_LIST_DEFAULT_LIMIT = 20
DOC_TRANSLATE_LIST_MAX_LIMIT = 50
DOC_TRANSLATE_SEGMENTS_MAX_RETURN = 5000
