/** Document translation dict codes and status values (aligned with backend constants). */

export const TRANSLATE_STATUS_DICT_CODE = 'TRANSLATE_STATUS'
export const TRANSLATE_SEGMENT_STATUS_DICT_CODE = 'TRANSLATE_SEGMENT_STATUS'

export const DOC_TRANSLATE_STATUS_PENDING = 'PENDING'
export const DOC_TRANSLATE_STATUS_OCR_RUNNING = 'OCR_RUNNING'
export const DOC_TRANSLATE_STATUS_EXTRACTING = 'EXTRACTING'
export const DOC_TRANSLATE_STATUS_TRANSLATING = 'TRANSLATING'
export const DOC_TRANSLATE_STATUS_ASSEMBLING = 'ASSEMBLING'
export const DOC_TRANSLATE_STATUS_SUCCESS = 'SUCCESS'
export const DOC_TRANSLATE_STATUS_FAILED = 'FAILED'

export const DOC_TRANSLATE_JOB_STATUS_VALUES = [
  DOC_TRANSLATE_STATUS_PENDING,
  DOC_TRANSLATE_STATUS_OCR_RUNNING,
  DOC_TRANSLATE_STATUS_EXTRACTING,
  DOC_TRANSLATE_STATUS_TRANSLATING,
  DOC_TRANSLATE_STATUS_ASSEMBLING,
  DOC_TRANSLATE_STATUS_SUCCESS,
  DOC_TRANSLATE_STATUS_FAILED,
] as const

export const DOC_TRANSLATE_SEGMENT_PENDING = 'PENDING'
export const DOC_TRANSLATE_SEGMENT_DONE = 'DONE'
export const DOC_TRANSLATE_SEGMENT_FAILED = 'FAILED'

export const DOC_TRANSLATE_SEGMENT_STATUS_VALUES = [
  DOC_TRANSLATE_SEGMENT_PENDING,
  DOC_TRANSLATE_SEGMENT_DONE,
  DOC_TRANSLATE_SEGMENT_FAILED,
] as const
