/**
 * 围栏代码块 `` ```lang `` 与 Prism 注册名对齐；未列出则原样传入（Prism 不识别时由渲染层回退）。
 */
const PRISM_LANG_ALIASES: Record<string, string> = {
  ts: 'typescript',
  tsx: 'tsx',
  js: 'javascript',
  jsx: 'jsx',
  mjs: 'javascript',
  cjs: 'javascript',
  py: 'python',
  python3: 'python',
  rb: 'ruby',
  rs: 'rust',
  sh: 'bash',
  shell: 'bash',
  zsh: 'bash',
  bash: 'bash',
  yml: 'yaml',
  yaml: 'yaml',
  md: 'markdown',
  json: 'json',
  jsonc: 'json',
  html: 'markup',
  htm: 'markup',
  xml: 'markup',
  svg: 'markup',
  vue: 'markup',
  cpp: 'cpp',
  'c++': 'cpp',
  cxx: 'cpp',
  cc: 'cpp',
  c: 'c',
  h: 'cpp',
  csharp: 'csharp',
  cs: 'csharp',
  kt: 'kotlin',
  kts: 'kotlin',
  swift: 'swift',
  sql: 'sql',
  ps1: 'powershell',
  pwsh: 'powershell',
  powershell: 'powershell',
  dockerfile: 'docker',
  docker: 'docker',
  diff: 'diff',
  patch: 'diff',
  go: 'go',
  golang: 'go',
  java: 'java',
  scala: 'scala',
  php: 'php',
  r: 'r',
  lua: 'lua',
  perl: 'perl',
  pl: 'perl',
  clj: 'clojure',
  cljs: 'clojure',
  ex: 'elixir',
  exs: 'elixir',
  hs: 'haskell',
  fs: 'fsharp',
  fsharp: 'fsharp',
  vb: 'vbnet',
  dart: 'dart',
  zig: 'zig',
  toml: 'toml',
  ini: 'ini',
  properties: 'properties',
  graphql: 'graphql',
  gql: 'graphql',
}

/** 将 Markdown 围栏语言标签规范为 Prism 语言 id。 */
export function normalizePrismLanguage(raw: string): string {
  const k = raw.toLowerCase().trim()
  return PRISM_LANG_ALIASES[k] ?? k
}
